version: '2'

services:
  web:
    build: .
    expose:
      - 5000
    volumes:
      - .:/app
    command: "gunicorn -w 4 -b 0.0.0.0:5000 app:app"
  nginx:
    image: nginx:1.13.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    volumes_from:
      - web
    depends_on:
      - web

