# Generated by Django 2.2.2 on 2019-06-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190603_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
