# Generated by Django 2.2.2 on 2019-06-03 17:24

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190603_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, max_length=512, null=True, populate_from=['name'], unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
