# Generated by Django 2.2.2 on 2019-06-04 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alternatives', to='core.Item'),
        ),
    ]
