# Generated by Django 2.2.2 on 2019-06-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190604_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_cached',
        ),
        migrations.AddField(
            model_name='item',
            name='cached_date',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
