# Generated by Django 2.2.2 on 2019-06-04 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190604_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cached_date',
        ),
    ]
