# Generated by Django 2.2.2 on 2019-06-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_item_cached_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cached_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
