# Generated by Django 2.2.2 on 2019-06-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_cached_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cached_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='items', to='core.Color'),
        ),
    ]
