# Generated by Django 2.2.2 on 2019-10-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191031_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_processing',
            field=models.IntegerField(blank=True),
        ),
    ]
