# Generated by Django 2.2.2 on 2019-10-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191031_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_processing',
            field=models.IntegerField(default=0),
        ),
    ]
