# Generated by Django 2.2.2 on 2019-11-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191031_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='update_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='platform',
            field=models.CharField(blank=True, choices=[('amazon', 'Amazon'), ('ebay', 'Ebay'), ('bestbuy', 'BestBuy'), ('wallmart', 'WallMart'), ('newegg', 'NewEgg')], default='amazon', max_length=32, null=True),
        ),
    ]
