# Generated by Django 2.2.2 on 2019-11-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_item_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('category_url', models.TextField(blank=True, null=True)),
                ('last_tracked_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='asin',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
