# Generated by Django 2.2.2 on 2019-11-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20191102_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchpage',
            name='cur_page',
            field=models.IntegerField(default=1),
        ),
    ]
