# Generated by Django 2.2.2 on 2019-11-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_searchpage_cur_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='asin',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
